version: "3.0"

services:
  dev:
    build: .
    command: ["jekyll", "serve", "--incremental", "--livereload"]
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - "./:/srv/jekyll"
